// @ts-check
// Cynhyrwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ReconnectSession(arg1) {
  return window['go']['main']['App']['ReconnectSession'](arg1);
}

export function ExecuteCommand(arg1,arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1,arg2);
}

export function ConnectSSH(arg1, arg2) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2);
}

export function CreateSessionProfile(arg1) {
  return window['go']['main']['App']['CreateSessionProfile'](arg1);
}

export function DeleteSessionProfile(arg1) {
  return window['go']['main']['App']['DeleteSessionProfile'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DownloadSFTPFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadSFTPFiles'](arg1, arg2, arg3);
}

export function DownloadLocalModel(arg1) {
  return window['go']['main']['App']['DownloadLocalModel'](arg1);
}

export function GetCloudProviderAuthSession(arg1) {
  return window['go']['main']['App']['GetCloudProviderAuthSession'](arg1);
}

export function GetReleaseVersion() {
  return window['go']['main']['App']['GetReleaseVersion']();
}

export function GetShellState() {
  return window['go']['main']['App']['GetShellState']();
}

export function GetSecureStorageStatus() {
  return window['go']['main']['App']['GetSecureStorageStatus']();
}

export function ImportSSHConfig(arg1) {
  return window['go']['main']['App']['ImportSSHConfig'](arg1);
}

export function LaunchSession(arg1) {
  return window['go']['main']['App']['LaunchSession'](arg1);
}

export function ListCloudModels(arg1, arg2) {
  return window['go']['main']['App']['ListCloudModels'](arg1, arg2);
}

export function ListSFTPFiles(arg1, arg2) {
  return window['go']['main']['App']['ListSFTPFiles'](arg1, arg2);
}

export function NavigateSFTP(arg1, arg2) {
  return window['go']['main']['App']['NavigateSFTP'](arg1, arg2);
}

export function ReadSFTPFile(arg1, arg2) {
  return window['go']['main']['App']['ReadSFTPFile'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveCloudProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCloudProvider'](arg1, arg2, arg3);
}

export function SaveLocalProvider(arg1) {
  return window['go']['main']['App']['SaveLocalProvider'](arg1);
}

export function SaveSFTPFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSFTPFile'](arg1, arg2, arg3);
}

export function SelectAIProvider(arg1) {
  return window['go']['main']['App']['SelectAIProvider'](arg1);
}

export function SendSSHInput(arg1, arg2) {
  return window['go']['main']['App']['SendSSHInput'](arg1, arg2);
}

export function SelectDownloadDirectory() {
  return window['go']['main']['App']['SelectDownloadDirectory']();
}

export function SelectUploadFiles() {
  return window['go']['main']['App']['SelectUploadFiles']();
}

export function StartCloudProviderAuth(arg1) {
  return window['go']['main']['App']['StartCloudProviderAuth'](arg1);
}

export function StartLocalModel() {
  return window['go']['main']['App']['StartLocalModel']();
}

export function StopLocalModel() {
  return window['go']['main']['App']['StopLocalModel']();
}

export function UploadSFTPFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadSFTPFiles'](arg1, arg2, arg3);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SendPlainChatMessage(arg1) {
  return window['go']['main']['App']['SendPlainChatMessage'](arg1);
}

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function UpdateCommandPolicy(arg1) {
  return window['go']['main']['App']['UpdateCommandPolicy'](arg1);
}

export function ResolveCommandPolicyRequest(arg1, arg2) {
  return window['go']['main']['App']['ResolveCommandPolicyRequest'](arg1, arg2);
}

export function AcceptSSHHostKey(arg1) {
  return window['go']['main']['App']['AcceptSSHHostKey'](arg1);
}

export function EnsureMasterPassword(arg1) {
  return window['go']['main']['App']['EnsureMasterPassword'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateCredentialPath(arg1, arg2) {
  return window['go']['main']['App']['ValidateCredentialPath'](arg1, arg2);
}
